In [4]:
import pandas as pd
import numpy as np

In [5]:
dataset = pd.read_csv('/kaggle/input/fraud-detection/fraudTrain.csv')

In [6]:
dataset.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [7]:
dataset.shape

(1296675, 23)

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [9]:
dataset.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [10]:
dataset.duplicated().any()

False

In [11]:
dataset.category.value_counts()

category
gas_transport     131659
grocery_pos       123638
home              123115
shopping_pos      116672
kids_pets         113035
shopping_net       97543
entertainment      94014
food_dining        91461
personal_care      90758
health_fitness     85879
misc_pos           79655
misc_net           63287
grocery_net        45452
travel             40507
Name: count, dtype: int64

In [12]:
dataset = dataset.drop(columns=['Unnamed: 0', 'cc_num', 'first', 'last', 'street', 'city', 'state', 'zip', 'trans_num', 'unix_time', 'job', 'merchant'])

In [13]:
dataset.head()

,trans_date_trans_time,category,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,misc_net,4.97,F,36.0788,-81.1781,3495,1988-03-09,36.011293,-82.048315,0
1,2019-01-01 00:00:44,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0
2,2019-01-01 00:00:51,entertainment,220.11,M,42.1808,-112.2620,4154,1962-01-19,43.150704,-112.154481,0
3,2019-01-01 00:01:16,gas_transport,45.00,M,46.2306,-112.1138,1939,1967-01-12,47.034331,-112.561071,0
4,2019-01-01 00:03:06,misc_pos,41.96,M,38.4207,-79.4629,99,1986-03-28,38.674999,-78.632459,0

# Feature Engineering

In [14]:
dataset['trans_date_trans_time'].dtype

dtype('O')

In [15]:
dataset['trans_date_trans_time'] = pd.to_datetime(dataset['trans_date_trans_time'])

In [16]:
dataset['year'] = dataset['trans_date_trans_time'].dt.year
dataset['month'] = dataset['trans_date_trans_time'].dt.month
dataset['day'] = dataset['trans_date_trans_time'].dt.day
dataset['hour'] = dataset['trans_date_trans_time'].dt.hour
dataset['minute'] = dataset['trans_date_trans_time'].dt.minute

dataset = dataset.drop(columns=['trans_date_trans_time'])

In [17]:
dataset.head()

,category,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud,year,month,day,hour,minute
0,misc_net,4.97,F,36.0788,-81.1781,3495,1988-03-09,36.011293,-82.048315,0,2019,1,1,0,0
1,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,2019,1,1,0,0
2,entertainment,220.11,M,42.1808,-112.2620,4154,1962-01-19,43.150704,-112.154481,0,2019,1,1,0,0
3,gas_transport,45.00,M,46.2306,-112.1138,1939,1967-01-12,47.034331,-112.561071,0,2019,1,1,0,1
4,misc_pos,41.96,M,38.4207,-79.4629,99,1986-03-28,38.674999,-78.632459,0,2019,1,1,0,3

In [18]:
dataset.head()

,category,amt,gender,lat,long,city_pop,dob,merch_lat,merch_long,is_fraud,year,month,day,hour,minute
0,misc_net,4.97,F,36.0788,-81.1781,3495,1988-03-09,36.011293,-82.048315,0,2019,1,1,0,0
1,grocery_pos,107.23,F,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,2019,1,1,0,0
2,entertainment,220.11,M,42.1808,-112.2620,4154,1962-01-19,43.150704,-112.154481,0,2019,1,1,0,0
3,gas_transport,45.00,M,46.2306,-112.1138,1939,1967-01-12,47.034331,-112.561071,0,2019,1,1,0,1
4,misc_pos,41.96,M,38.4207,-79.4629,99,1986-03-28,38.674999,-78.632459,0,2019,1,1,0,3

In [19]:
from datetime import datetime
today = datetime.today()
dataset['dob'] = pd.to_datetime(dataset['dob'])

dataset['age'] = today.year - dataset['dob'].dt.year

dataset['age'] -= ((today.month & today.day) < (dataset['dob'].dt.month & dataset['dob'].dt.day))

dataset = dataset.drop(columns=['dob'])

# Encoding Categorical Data

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['category'] = le.fit_transform(dataset['category'])
dataset['gender'] = le.fit_transform(dataset['gender'])

In [21]:
dataset.head()

,category,amt,gender,lat,long,city_pop,merch_lat,merch_long,is_fraud,year,month,day,hour,minute,age
0,8,4.97,0,36.0788,-81.1781,3495,36.011293,-82.048315,0,2019,1,1,0,0,36
1,4,107.23,0,48.8878,-118.2105,149,49.159047,-118.186462,0,2019,1,1,0,0,45
2,0,220.11,1,42.1808,-112.2620,4154,43.150704,-112.154481,0,2019,1,1,0,0,62
3,2,45.00,1,46.2306,-112.1138,1939,47.034331,-112.561071,0,2019,1,1,0,1,57
4,9,41.96,1,38.4207,-79.4629,99,38.674999,-78.632459,0,2019,1,1,0,3,38

In [22]:
dataset = dataset.drop(columns=['lat', 'long', 'merch_lat', 'merch_long'])

In [23]:
dataset.head()

,category,amt,gender,city_pop,is_fraud,year,month,day,hour,minute,age
0,8,4.97,0,3495,0,2019,1,1,0,0,36
1,4,107.23,0,149,0,2019,1,1,0,0,45
2,0,220.11,1,4154,0,2019,1,1,0,0,62
3,2,45.00,1,1939,0,2019,1,1,0,1,57
4,9,41.96,1,99,0,2019,1,1,0,3,38

In [24]:
dataset.is_fraud.value_counts()

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

# ImBalanced Data
# OverSampling using SMOTE

In [25]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

X = dataset.drop('is_fraud', axis=1)
y = dataset['is_fraud']

smote = SMOTE()
X_res, y_res = smote.fit_resample(X, y)

In [26]:
y_res.value_counts()

is_fraud
0    1289169
1    1289169
Name: count, dtype: int64

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)

In [28]:
X_train

,category,amt,gender,city_pop,year,month,day,hour,minute,age
2405787,12,1371.915506,0,892,2019,7,9,22,10,24
1614448,11,1056.579250,0,1761,2019,5,22,15,44,58
1366567,4,348.872026,1,716,2019,8,25,9,16,57
2138973,9,15.326980,0,144160,2019,6,18,20,50,39
356496,1,98.020000,1,899,2019,6,15,22,41,56
...,...,...,...,...,...,...,...,...,...,...
110268,2,72.380000,0,1478,2019,3,4,2,49,59
1692743,2,12.819101,0,1646,2019,3,2,2,41,40
2356330,3,13.379540,0,302,2020,6,19,9,12,34
2229084,4,350.784042,0,1412,2020,1,4,3,7,54
2219110,11,990.553358,0,8007,2019,7,29,22,37,84

In [29]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(criterion='entropy', random_state=42)
DT.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [30]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
y_pred = DT.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))

0.9932359580195009
0.9898681359214349
0.9967077011165187
0.9932761445783133

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[254549,   2637],
       [   851, 257631]])

In [49]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 25, criterion= 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=25, random_state=42)

In [50]:
y_pred_r = classifier.predict(X_test)
print(accuracy_score(y_test, y_pred_r))
print(precision_score(y_test, y_pred_r))
print(recall_score(y_test, y_pred_r))
print(f1_score(y_test, y_pred_r))

0.9978358168433954
0.9965733072987011
0.9991179269736384
0.9978439948688622

In [53]:
cm = confusion_matrix(y_test, y_pred_r)
cm

array([[256298,    888],
       [   228, 258254]])